### ISSUE TITLE
pull requesting new option to main project?

### ISSUE THREAD

**Issue by developer861** [LuckyLuke-a/Xray-core#1]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

can you pull request these new features to main project?

### Reproduction Method

.

### Client config

.

### Server config

.

### Client log

.

### Server log

.

**Comment by LuckyLuke-a** [comment]
Please see: https://github.com/XTLS/Xray-core/pull/3738

**Comment by developer861** [comment]
oh  sorry i didn't see that :/

looks like they have problems with the other parts but how about pull requesting Fake Packet Transmission 

https://github.com/XTLS/Xray-core/pull/3738#issuecomment-2333746043

the develper here said that it's a good option

**Comment by LuckyLuke-a** [comment]
داداش پیاده سازی فیک پکت چندان پیچیده نیست, از طرفی کدها رو دارن اگر بخوان هر قسمت رو اضافه میکنن

**Comment by developer861** [comment]
> داداش پیاده سازی فیک پکت چندان پیچیده نیست, از طرفی کدها رو دارن اگر بخوان هر قسمت رو اضافه میکنن

متوجهم منم issue زدم بهشون برای اضافه کردن ولی گفتم شاید خودتون بخواین pr بزنین چون ایده ازخودتون بوده 
اگه pr هم بزنین سریعتر اضافه میشه
بازم دمتون گرم❤️
https://github.com/XTLS/Xray-core/issues/4036#issue-2674994991

**Comment by LuckyLuke-a** [comment]
داداش ذمت گرم بابت پیگیریت ولی ختی اگه فیک پکت اضافه هم بشه دردی رو از ریلیتی دوا نمیکنه, مشکل اصلی و چیزی که باعث فیلتر شدن میشه [uTLS](https://github.com/refraction-networking/utls) هست که ویژگی های هندشیکش (کلاینت هلوش) شناسایی شده, ( همونطور که میدونی هسته ایکس ری از uTLS استفاده میکنه) البته تو هسته ای که تو گیتهابم قرار دادم یسری تغییرات **ریز** رو uTLS دادم که فعلا کاری به کارش ندارن
