### ISSUE TITLE
Upgrade to latest pre-release (for Xhttp)

### ISSUE THREAD

**Issue by Graveyard9988** [LuckyLuke-a/Xray-core#2]
Also Please enable these for Xhttp: (fragment for splithttp [download] & fake packets for reality of this xhttp [upload])
Also provide documentation.

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

Regards

### Reproduction Method

.

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by LuckyLuke-a** [comment]
Unfortunately currently i do not any plan for it!
